### ISSUE TITLE
instructions don't say where to use the other user's id to create a follow

### ISSUE THREAD

**Issue by drewp** [vole/vole#50]
I was unable to perform https://github.com/vole/vole#following-others because I couldn't find where to put the read-only ID of the person I wanted to follow. The instructions never mention using that id anywhere.

'name it whatever you like' is also a bad instruction, since at this point, I don't know what that folder will be used for. I called mine 'ext' thinking it might be for data external to my computer, but what do I know?

In BT Sync, I successfully added /home/drewp/Vole/users/ext with a new secret, which I think might now be my own ID. Then I ran
mkdir /home/drewp/Vole/users/RA32XLBBHXMWMECGJAJSJMMPQ3Z2ZGR7K
but I don't know where to add that in BT Sync. I tried adding it with yet another secret.

**Comment by marktheunissen** [comment]
Thanks for the feedback, I have updated the README with clearer instructions, as I agree it was a little opaque before. 

Let's say you're following Vole Team account. You should start by making an empty directory so that you have:

```
 /home/drewp/Vole/users/voleteam
```

Then, open the BitTorrent Sync interface, and add a shared folder. Paste the Vole Team read-only key into the "shared secret" field, and select the `/home/drewp/Vole/users/voleteam` folder in the other field:

![screen shot 2013-06-23 at 10 22 29 am](https://f.cloud.github.com/assets/453297/692312/c113737a-dc18-11e2-84e4-dee7e0507c08.png)

Let me know if you have other issues. This process is obviously very tedious and we'd love to automate it as soon as BTSync provides an API.
